# Generated by Django 4.0.3 on 2022-04-10 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Guild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=100, verbose_name="Guild name")),
                ("description", models.TextField(verbose_name="Guild description")),
            ],
            options={
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="GuildMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=100)),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        choices=[("ADMIN", "Admin"), ("MODERATOR", "Moderator")],
                        default="",
                        max_length=21,
                        null=True,
                        verbose_name="User position",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GuildTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Team in guild"),
                ),
                ("description", models.TextField(verbose_name="Team description")),
            ],
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=100)),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        choices=[("ADMIN", "Admin"), ("MODERATOR", "Moderator")],
                        default="",
                        max_length=21,
                        null=True,
                        verbose_name="User position",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="guild.guildteam",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
