# Generated by Django 4.0.3 on 2022-04-12 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("guild", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guildmember",
            name="guild",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guild_members",
                to="guild.guild",
                verbose_name="Guild",
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_members",
                to="guild.guildteam",
            ),
        ),
    ]
